# netlify.toml

# This new build section is for debugging the dependency issue.
[build]
  command = "echo '--- Listing files in root directory ---' && ls -la && echo '--- Displaying .tool-versions content ---' && cat .tool-versions && echo '--- Installing dependencies now ---' && pip install -r requirements.txt"

# Your existing functions configuration remains the same.
[functions]
  directory = "netlify/functions/"

[functions."get-job-links"]
  schedule = "0 8 * * *"

[functions."process-job-links"]
  schedule = "*/2 * * * *"
