# netlify.toml

# Final debug attempt: Install all packages manually.
# NOTE: The requirements.txt file MUST be deleted for this to work.
[build]
  command = "pip install requests beautifulsoup4 netlify-blobs"

[build.environment]
  PYTHON_VERSION = "3.11"

# Your functions configuration remains the same.
[functions]
  directory = "netlify/functions/"

[functions."get-job-links"]
  schedule = "0 8 * * *"

[functions."process-job-links"]
  schedule = "*/2 * * * *"
