# netlify.toml

# Each scheduled function is defined in its own block.
# The general [functions] block was removed to fix the TOML syntax error.
# The 'directory' will default to 'netlify/functions/', which is what you're using.

# Schedule for the function that GETS the job links
[[functions]]
  schedule = "0 8 * * *"
  name = "get-job-links"

# Schedule for the function that PROCESSES a batch of job links
[[functions]]
  schedule = "*/2 * * * *"
  name = "process-job-links"
