# netlify.toml

# Define global settings for all functions.
# The directory is the default, but we declare it for clarity.
[functions]
  directory = "netlify/functions/"

# Configure the 'get-job-links' function specifically
[functions."get-job-links"]
  # Schedule it to run at 8:00 AM daily
  schedule = "0 8 * * *"

# Configure the 'process-job-links' function specifically
[functions."process-job-links"]
  # Schedule it to run every 2 minutes
  schedule = "*/2 * * * *"
