# netlify.toml

# Main configuration for functions
[functions]
  included_files = ["!**/__pycache__/**"] # Exclude Python cache files
  # This tells Netlify where to find your function handlers
  directory = "netlify/functions/"

# Schedule for the function that GETS the job links
[[functions.scheduled]]
# Cron expression for "at 8:00 AM every day"
cron = "0 8 * * *"
function = "get-job-links"

# Schedule for the function that PROCESSES a batch of job links
[[functions.scheduled]]
# Cron expression for "every 2 minutes" to process in batches
cron = "*/2 * * * *"
function = "process-job-links"
