# netlify.toml

# This new build command attempts to manually run the installation steps.
[build]
  command = "mise use python@3.11.13 && mise install && pip install -r requirements.txt"

# Your existing functions configuration remains the same.
[functions]
  directory = "netlify/functions/"

[functions."get-job-links"]
  schedule = "0 8 * * *"

[functions."process-job-links"]
  schedule = "*/2 * * * *"
