# netlify.toml

# Main configuration for functions
[functions]
  included_files = ["!**/__pycache__/**"]
  directory = "netlify/functions/"

# Schedule for the function that GETS the job links
[[functions]]
  # The schedule uses cron syntax
  schedule = "0 8 * * *"
  # The name of the function file (without .py)
  name = "get-job-links"

# Schedule for the function that PROCESSES a batch of job links
[[functions]]
  schedule = "*/2 * * * *"
  name = "process-job-links"
