# netlify.toml

[build]
  # The root directory of your site, where index.html is located.
  publish = "."

[functions]
  # The directory where your Python function files are located.
  directory = "netlify/functions/"
