# netlify.toml

# This new approach sets the Python version using an environment variable
# instead of a build command.
[build.environment]
  PYTHON_VERSION = "3.11"

# Your functions configuration remains the same.
[functions]
  directory = "netlify/functions/"

[functions."get-job-links"]
  schedule = "0 8 * * *"

[functions."process-job-links"]
  schedule = "*/2 * * * *"
