[build]
  # This tells Netlify where to find your site's files.
  # Since index.html is in the root, we can set it to the root.
  publish = "." 

[functions]
  # This tells Netlify where to find your function files.
  directory = "netlify/functions/"
